stages:
  train:
    cmd: 
    - python train.py data/
    deps:
    - data/
    - train.py
    - requirements.txt
    params:
    - params.yaml:
    metrics:
    - evaluation.json:
        cache: false
    outs:
    - model
    plots:
    - dvclive/scalars/eval/accuracy.tsv:
        cache: false
        x: step
        y: eval/accuracy
    - dvclive/scalars/train/accuracy.tsv:
        cache: false
        x: step
        y: train/accuracy
    - dvclive/scalars/eval/loss.tsv:
        cache: false
        x: step
        y: eval/loss
    - dvclive/scalars/train/loss.tsv:
        cache: false
        x: step
        y: train/loss
  inference:
    cmd: python inference.py data/
    deps:
    - data
    - model
    - inference.py
    outs:
    - predictions
    plots:
    - mispredicted
