plots:
    - mispredicted
    - loss:
        y:
          evaluation/plots/metrics/train/loss.tsv: train/loss
          evaluation/plots/metrics/eval/loss.tsv: eval/loss
    - accuracy:
        y:
          evaluation/plots/metrics/train/accuracy.tsv: train/accuracy
          evaluation/plots/metrics/eval/accuracy.tsv: eval/accuracy
metrics:
    - evaluation/metrics.json
params:
    - params.yaml
stages:
  train:
    cmd: 
    - python train.py data/
    deps:
    - data/
    - train.py
    - requirements.txt
    - params.yaml
    outs:
    - model
    - evaluation:
        cache: false
  inference:
    cmd: python inference.py data/
    deps:
    - data
    - model
    - inference.py
    outs:
    - predictions
    - mispredicted
