stages:
  train:
    cmd: 
    - python train.py
    deps:
    - data/.ldb_workspace
    - train.py
    - requirements.txt
    params:
    - epochs
    metrics:
    - dvclive.json:
        cache: false
    - evaluation.json:
        cache: false
    outs:
    - model
    plots:
    - dvclive/scalars/eval/accuracy.tsv:
        cache: false
        x: step
        y: eval/accuracy
    - dvclive/scalars/train/accuracy.tsv:
        cache: false
        x: step
        y: train/accuracy
    - dvclive/scalars/eval/loss.tsv:
        cache: false
        x: step
        y: eval/loss
    - dvclive/scalars/train/loss.tsv:
        cache: false
        x: step
        y: train/loss
  inference:
    cmd: python inference.py ./data
    deps:
    - model
    - inference.py
    outs:
    - predictions
  misclassification:
    cmd: 
    - ldb index predictions/ --annotation-update merge
    - ldb instantiate ds:root --query 'inference.confidence > `0.9` && label != inference.label' --target ./mispredicted
    - mv mispredicted/*.json mispredicted-json/
    deps:
    - predictions
    outs:
    - mispredicted-json/
    plots:
    - mispredicted/
    