name: Experiment Runner
on: push
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner launch --single \
            --cloud-spot \
            --labels=cml \
            --cloud=aws \
            --cloud-region=us-west-2 \
            --cloud-gpu=v100 \
            --cloud-hdd-size=100 \
            --cloud-type=l
  runner-job:
    needs: deploy-runner
    runs-on: [ self-hosted, cml ]
    container:
      image: iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Setup project
          pip install -r requirements.txt

          # Get data and artifacsts from DVC remote
          dvc pull

          # Run pipeline
          dvc repro

          # Compare metrics to main
          git fetch --prune

          echo "# Metrics" >> report.md
          dvc metrics diff --show-md main >> report.md

          # Create report
          cml comment create report.md

          # Create Pull Request with code and metadata changes
          cml pr create .

          # Push new data and artifacts to DVC remote
          dvc push
